### ISSUE TITLE
Panic in ShowToolTipAtMousePosition

### ISSUE THREAD

**Issue by williambrode** [dweymouth/fyne-tooltip#2] opened 2024-10-08 18:43 UTC
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x1c752cc]

goroutine 8285 [running]:
github.com/dweymouth/fyne-tooltip/internal.ShowToolTipAtMousePosition({0x0, 0x0}, {0x9103b30?, 0xc0?}, {0x22b9447, 0x1a})
	github.com/dweymouth/fyne-tooltip@v0.2.0/internal/tooltip_layer.go:73 +0xac
github.com/dweymouth/fyne-tooltip/widget.(*toolTipContext).setPendingToolTip.func1()
	github.com/dweymouth/fyne-tooltip@v0.2.0/widget/tooltipwidget.go:142 +0x157
created by github.com/dweymouth/fyne-tooltip/widget.(*toolTipContext).setPendingToolTip in goroutine 3262
	github.com/dweymouth/fyne-tooltip@v0.2.0/widget/tooltipwidget.go:131 +0x10f

**Comment by dweymouth** [comment] 2024-10-08 19:55
Can you share a complete code snippet that reproduces the failure? Are you calling that func directly or using it via ToolTipWidget / ToolTipWidgetExtend?

**Comment by williambrode** [comment] 2024-10-08 20:49
This is the full backtrace I got in sentry.  So I don't actually know more than you do.  Often just looking at the code reveals only a single way the panic could happen so I hoped that might be the case here.  We use several of the built-in tooltip widgets and I wrote one custom one - I think its in your Readme - but had a typo or two.

```go
package widgets

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/widget"
	ttwidget "github.com/dweymouth/fyne-tooltip/widget"
)

type ToolTipIcon struct {
	widget.Icon
	ttwidget.ToolTipWidgetExtend
}

func NewToolTipIcon(resource fyne.Resource) *ToolTipIcon {
	w := &ToolTipIcon{
		Icon: widget.Icon{
			Resource: resource,
		},
	}
	w.ExtendBaseWidget(w)
	return w
}

func (w *ToolTipIcon) ExtendBaseWidget(wid fyne.Widget) {
	w.ExtendToolTipWidget(wid)
	w.Icon.ExtendBaseWidget(wid)
}
```

**Comment by dweymouth** [comment] 2024-10-09 23:01
This seems to be caused by the canvas being nil for a widget. I pushed a fix so it won't crash, but it still won't be able to show a tool tip in this case. Not sure why Fyne is returning a nil canvas for your widget

**Comment by dweymouth** [comment] 2024-10-10 18:40
Closing since it should not crash anymore. Tagged v0.2.1

**Closed as completed by dweymouth** 2024-10-10 18:40 UTC
